% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[left=3cm,right=3cm,top=2.5cm,bottom=2.5cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{caption}
\captionsetup[table]{skip=6pt}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
% Paragraph scaffolding for manuscript revision.
%
% Two environments, presented in this order per paragraph:
%
%   rgt   -- author's rewrite (initially a placeholder)
%            small, italic, dark blue
%   orig  -- original Claude-authored draft, and until the rewrite
%            replaces it, the body text of the manuscript
%            normal size, gray
%
% The `bullets' environment (a boiled-down topic sentence plus bullet
% points, one per paragraph) is no longer used inside manuscripts:
% those blocks now live in a companion bullets.Rmd supplement in the
% same report directory, which typesets them as plain \textbf{} +
% itemize and needs no part of this file. The definition is retained
% only so that a stray block left in a document still compiles.
%
% This file is identical across every manuscript that includes it.
% It previously existed in two variants that swapped the sizes of
% rgt and orig, so the same markup rendered differently depending on
% which repository the manuscript lived in. The variant retained here
% keeps orig at full size because orig, not rgt, currently carries
% the prose in every manuscript in the pool.

\usepackage{xcolor}

\newcounter{pgraph}

\newenvironment{bullets}{%
  \stepcounter{pgraph}%
  \begin{quote}\small\sffamily\color[gray]{0.30}%
  {\normalfont\scriptsize\color[gray]{0.58}[\thepgraph]\enspace}}{%
  \end{quote}}

\newenvironment{rgt}{%
  \begin{quote}\small\itshape\color[RGB]{20,60,160}}{%
  \end{quote}}

\newenvironment{orig}{%
  \begin{quote}\normalsize\color[gray]{0.55}}{%
  \end{quote}}

% backward compat alias
\newenvironment{claudecode}{\begin{orig}}{\end{orig}}
%% tools/stamp.tex
%% Provenance footer for PDFs rendered from this project.
%% Vendored by zzcollab; this file is not project-specific. The
%% footer prints the source document and the time of rendering.
%% The git version is defined here too, and so is available to a
%% project that wants it on the page, but it is left off the
%% default footer: it already names the staged copy in share/ and
%% appears in its manifest row. All values are supplied at render
%% time by tools/stamp-render.R, which writes a small generated
%% file that redefines the macros below. The \providecommand
%% defaults keep a bare LaTeX compile working when the document is
%% built without the wrapper.
\usepackage{fancyhdr}
\usepackage{xcolor}
\providecommand{\stampsource}{\detokenize{(source not recorded)}}
\providecommand{\stamptime}{(time not recorded)}
\providecommand{\stampversion}{\detokenize{(version not recorded)}}
\setlength{\footskip}{40pt}
\newcommand{\stampfootcontent}{%
  \footnotesize\color{gray}%
  \parbox[b]{\textwidth}{%
    \stamptime\hfill\thepage\\[2pt]%
    \ttfamily\raggedright\stampsource}}
\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\stampfootcontent}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
%% The title page uses the `plain` page style; redefine it so the
%% stamp appears there too.
\fancypagestyle{plain}{%
  \fancyhf{}%
  \fancyfoot[C]{\stampfootcontent}%
  \renewcommand{\headrulewidth}{0pt}%
  \renewcommand{\footrulewidth}{0.4pt}}
\renewcommand{\stampsource}{\textasciitilde{}/\allowbreak{}prj/\allowbreak{}res/\allowbreak{}04-runin-power-analysis/\allowbreak{}runinpower/\allowbreak{}analysis/\allowbreak{}report/\allowbreak{}04-gls-vs-ttest/\allowbreak{}report.Rmd}
\renewcommand{\stamptime}{2026-08-15 16:32 PDT}
\renewcommand{\stampversion}{\detokenize{455c889-wip}}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{float}
\usepackage[mathlines]{lineno}
\linenumbers
\DeclareMathOperator{\Var}{Var}
\DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator{\E}{E}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
% fallback for those not using the hyperref driver hyperxmp:
\makeatletter
\@ifundefined{xmpquote}{\newcommand{\xmpquote}[1]{#1}}{}
\makeatother
\hypersetup{
  pdftitle={GLS versus Averaged Change-Score Estimators for Clinical Trials with Run-In Observations},
  pdfauthor={Ronald G. Thomas, Ph.D.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{GLS versus Averaged Change-Score Estimators for
Clinical Trials with Run-In Observations}
\author{Ronald G. Thomas, Ph.D.\thanks{Wertheim School of Public Health, UCSD; ORCID: 0000-0003-1686-4965}}
\date{August 15, 2026}

\begin{document}
\maketitle
\begin{abstract}
\textbf{Background.} Three estimators of the treatment effect in
longitudinal trials with run-in observations are in routine
use: the GLS estimator under the linear mixed model, which
exploits the full covariance structure to extract maximum
information from all observations; the ANCOVA estimator,
which regresses post-randomization means on the run-in mean
as a covariate without specifying the random-effects
covariance; and the averaged change-score estimator, which
computes a simple difference of phase means and applies a
\(t\)-test, requiring no variance-component estimation. The
relative efficiency of these estimators under correct and
misspecified models has not been comprehensively
characterized.
\textbf{Methods.} We derive the variance of the three
estimators as a function of the trial design
\((J_0, J_1, J_2)\) and the variance parameters
\((\sigma^2, \sigma_b^2)\). The derivation proceeds via the
Woodbury-based variance formulas of Paper 1 in this
compendium, plus closed-form expressions for the ANCOVA
and averaged-change-score variances under the same
random-slopes model. Robustness to misspecification of the
within-subject covariance (\(R\)) and the random-effects
covariance (\(G\)) is assessed analytically through sandwich
variances, and a Monte Carlo simulation under compound
symmetry evaluates the estimators alongside a GLS analysis
that misstates the random-slope variance.
\textbf{Results.} All comparisons are made on the common
estimand scale, with the averaged and ANCOVA contrasts
rescaled to unbiasedness for the treatment effect
\(\gamma\). Under correct specification, GLS \(\le\) ANCOVA
\(\le\) averaged in variance, with no violations over a
115-cell grid of designs and signal-to-noise ratios. The
efficiency penalty of the simpler estimators is
substantial in run-in designs with multiple
treatment-period visits: at
\((J_0, J_1, J_2) = (2, 2, 0)\) the relative efficiency of
ANCOVA versus GLS is 0.64 to 0.81 across signal-to-noise
ratios, an efficiency loss of 19\% to 36\%. Relative
efficiency above 0.95 occurs only in single-post-visit
run-in designs (\(J_1 = 1\), \(J_2 = 0\)) and in designs
without run-in or common close (\(J_0 = 0\), \(J_2 = 0\)) at
high signal-to-noise. In the MIRIAD-based example the
ANCOVA sample size exceeds the GLS sample size by up to
a factor of roughly 2.6 among run-in designs, and the
averaged sample size by up to a factor of roughly 45.
Under the \(G\) and \(R\) misspecifications studied, GLS
never loses its advantage over the simpler estimators:
the misspecified-GLS sandwich variance peaks at 5.3
against an averaged-estimator variance of 8.9 at the
reference design.
\textbf{Conclusions.} GLS is the efficient estimator under
correct specification, and its advantage survives the
covariance misspecifications examined here. The averaged
change-score estimator remains useful as a fully
prespecified robust benchmark and a teaching tool. The
open robustness question, not studied here, is whether
feasible GLS with variance components estimated from
small samples retains this advantage.
\end{abstract}

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\setstretch{1.1}
\section{Introduction}\label{introduction}

\begin{orig}
The GLS estimator \(\hat\gamma_{\text{GLS}} =
(X'\Sigma^{-1}X)^{-1}X'\Sigma^{-1}\mathbf{c}\) is the
best linear unbiased estimator (minimum variance among
linear unbiased estimators) when \(\Sigma\) is
known. In practice, \(\Sigma\) must be estimated, and
the efficiency of the feasible GLS depends on the
accuracy of this estimation. With small sample sizes
or short follow-up, variance component estimates can
be unstable, potentially eroding the theoretical
advantage of GLS.

\end{orig}

The averaged change-score approach sidesteps variance
component estimation entirely. For a trial with \(J_0\)
run-in and \(J_2\) common close observations, the
estimator is:
\begin{equation}
  \hat\gamma_{\text{avg}} = \bar{d}_1 - \bar{d}_0
\end{equation}
where
\begin{equation}
  d_{ik} = \frac{1}{J_1 + J_2}
    \sum_{\ell=1}^{J_1+J_2} Y_{i,\ell,k}
    - \frac{1}{J_0}
    \sum_{\ell=1}^{J_0} Y_{i,-\ell,k}
\end{equation}
is the difference of the post-randomization and run-in
means for participant \(i\). The baseline visit is the
change-score reference and cancels, so it enters neither
average; this matches the contrast implemented in
\texttt{var\_gamma\_avg()}. Throughout, the code and figure
parameters use \((r, k, f)\) for the design counts, with
the correspondence \(J_0 = r\) (run-in), \(J_1 = k\)
(treatment period), and \(J_2 = f\) (common close); the
prose and table headers use \((J_0, J_1, J_2)\).

\begin{orig}
The debate between change-score and ANCOVA analyses has
a long history\textsuperscript{\citeproc{ref-senn2006}{1}--\citeproc{ref-crager1987}{3}}.\textsuperscript{\citeproc{ref-yang2001}{4}} provided a formal efficiency
comparison for pretest-posttest designs. The closest
antecedent of the present work is\textsuperscript{\citeproc{ref-frison1992}{5}}, who
derived the relative efficiency of post-treatment,
change-score, and ANCOVA analyses when several baseline
measurements are available, and\textsuperscript{\citeproc{ref-frison1997}{6}}, who
extended the treatment to repeated post-treatment
measurements. Their ordering, that ANCOVA on the mean of
the available baselines dominates the change score which
in turn dominates the raw post-treatment comparison, is
the qualitative result that the ordering established in
Section 3.1 specializes. What is new here is not the
ordering itself but the closed-form relative
efficiencies in the run-in random-slope parameterization:
the efficiency margins are obtained as explicit
functions of the design counts \((J_0, J_1, J_2)\) and the
signal-to-noise ratio \(\sigma_b/\sigma\), they cover a
post-treatment common close phase absent from the
Frison-Pocock setting, and the estimand is a difference
of slopes rather than a difference of means. Within the
run-in literature,\textsuperscript{\citeproc{ref-hu2021}{7}} derived GLS power formulas
for trials with pre-randomization observations, which
the present comparison takes as the efficient benchmark
against which the simpler estimators are measured.\textsuperscript{\citeproc{ref-liu2009}{8}} and\textsuperscript{\citeproc{ref-lu2010}{9}} compared baseline-as-covariate against
baseline-as-response (constrained longitudinal data
analysis).\textsuperscript{\citeproc{ref-tsiatis2008}{10}} developed a semiparametric
framework for covariate adjustment.\textsuperscript{\citeproc{ref-mallinckrodt2021}{11}}
showed that MMRM requires time-by-covariate interactions
to guarantee power gains over ANCOVA.\textsuperscript{\citeproc{ref-brogan1980}{12}}
established the foundational comparison of pretest-posttest
designs.\textsuperscript{\citeproc{ref-coffman2016}{13}} addressed conditioning on baseline
in longitudinal RCTs.\textsuperscript{\citeproc{ref-wang2019}{14}} proposed the two-period
approach for run-in trials.

\end{orig}

\begin{orig}
We note that the averaged change-score estimator
studied here is distinct from (and less efficient than)
the constrained longitudinal data analysis (cLDA)
estimator of\textsuperscript{\citeproc{ref-liang2000}{15}} and\textsuperscript{\citeproc{ref-lu2010}{9}}, which includes
baseline in the response vector with a common-mean
constraint. The cLDA estimator uses the full covariance
structure without requiring specification of the random
effects distribution \(G\), placing it between the
averaged estimator and GLS in the efficiency ordering.\textsuperscript{\citeproc{ref-funatogawa2020}{16}} extended the cLDA framework to pre-
and post-treatment measurements with equal baseline
assumptions. A full comparison including cLDA is beyond
the scope of this paper but represents a natural
extension.

\end{orig}

\begin{orig}
The \texttt{longpower} R package\textsuperscript{\citeproc{ref-iddi2022}{17}} provides the
CRAN reference implementation of power calculations for
the GLS / REML-based slope-comparison estimator,
covering the Liu-Liang\textsuperscript{\citeproc{ref-liuliang1997}{18}}, Diggle\textsuperscript{\citeproc{ref-diggle2002}{19}}, and Edland\textsuperscript{\citeproc{ref-ard2011}{20}} formulations.
These routines correspond to the \(\hat\gamma_{\text{GLS}}\)
estimator studied here under correct specification and
constitute the Paper 1 baseline extended by run-in and
common close observations. However, \texttt{longpower} does not
cover the ANCOVA-on-run-in-mean estimator or the
averaged change-score \(t\)-test, nor does it characterize
the efficiency loss from misspecification of \(G\) or \(R\).
The comparison developed here therefore complements
\texttt{longpower} by (i) ordering the three candidate
estimators under correct specification and (ii)
quantifying the efficiency margin that GLS retains
under the misspecifications of \(G\) and \(R\) studied
below.

\end{orig}

\section{Three estimators}\label{three-estimators}

\subsection{GLS under the mixed model}\label{gls-under-the-mixed-model}

\begin{orig}
From\textsuperscript{\citeproc{ref-frost2008}{21}}, the per-pair variance is the
\((\gamma, \gamma)\) element of
\((X'\Sigma^{-1}X)^{-1}\) with \(\Sigma = R + ZGZ'\)\textsuperscript{\citeproc{ref-laird1982}{22},\citeproc{ref-verbeke2000}{23}}, computed via the Woodbury
identity.

\end{orig}

For the Frost conventional design (\(J_0 = 0\), \(J_1 = 2\)):
\begin{equation}
  \hat\gamma_{\text{GLS}} = \frac{1}{2t}
    [(C_{22} + C_{21}) - (C_{12} + C_{11})]
\end{equation}
with \(\mathop{\mathrm{Var}}(\hat\gamma_{\text{GLS}}) =
(\sigma^2 + 2\sigma_b^2 t^2)/t^2\).

\subsection{\texorpdfstring{Averaged change score (\(t\)-test)}{Averaged change score (t-test)}}\label{averaged-change-score-t-test}

The averaged change-score estimator ignores the
within-subject correlation structure and treats
\(d_{ik}\) as independent observations:
\begin{equation}
  \mathop{\mathrm{Var}}(\hat\gamma_{\text{avg}})
  = \frac{2}{m}\mathop{\mathrm{Var}}(d_{ik})
\end{equation}

The variance \(\mathop{\mathrm{Var}}(d_{ik})\) depends on the correlation
structure but does not require its estimation. As an
estimator of \(\gamma\), the contrast is divided by the
design constant \(c\) derived in Section 3.1, and all
variances, relative efficiencies, and sample sizes
reported in this paper are on that common \(\gamma\)
scale.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a }\OtherTok{\textless{}{-}} \FloatTok{1.0}
\NormalTok{b }\OtherTok{\textless{}{-}} \FloatTok{1.0}
\NormalTok{tt }\OtherTok{\textless{}{-}} \FloatTok{1.0}

\CommentTok{\# gamma{-}scale rescaling constant (Section 3.1):}
\CommentTok{\# mean accumulated effect over post{-}randomization visits}
\NormalTok{cfac }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(r, k, f, }\AttributeTok{t\_interval =} \DecValTok{1}\NormalTok{) \{}
\NormalTok{  t\_interval }\SpecialCharTok{*}\NormalTok{ (k }\SpecialCharTok{*}\NormalTok{ (k }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{/} \DecValTok{2} \SpecialCharTok{+}\NormalTok{ k }\SpecialCharTok{*}\NormalTok{ f) }\SpecialCharTok{/}\NormalTok{ (k }\SpecialCharTok{+}\NormalTok{ f)}
\NormalTok{\}}

\NormalTok{v\_gls }\OtherTok{\textless{}{-}} \FunctionTok{var\_gamma\_matrix}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, a, b, tt)}
\NormalTok{v\_avg }\OtherTok{\textless{}{-}} \FunctionTok{var\_gamma\_avg}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, a, b, tt) }\SpecialCharTok{/}
  \FunctionTok{cfac}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, tt)}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{re }\OtherTok{\textless{}{-}}\NormalTok{ v\_gls }\SpecialCharTok{/}\NormalTok{ v\_avg}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}J\_0=2, J\_1=2: GLS=\%.4f, Avg=\%.4f, RE=\%.4f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{,}
\NormalTok{            v\_gls, v\_avg, re))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## J_0=2, J_1=2: GLS=2.1569, Avg=8.8889, RE=0.2426
\end{verbatim}

\subsection{ANCOVA with run-in mean as covariate}\label{ancova-with-run-in-mean-as-covariate}

The ANCOVA approach uses the averaged run-in rate as a
baseline covariate without specifying \(\sigma_b^2\):
\begin{equation}
  \bar{Y}_{i,\text{post}} = \alpha + \gamma g_i
    + \phi \bar{Y}_{i,\text{pre}} + \varepsilon_i
\end{equation}

The variance of \(\hat\gamma\) under this model is
\begin{equation}
  \mathop{\mathrm{Var}}(\hat\gamma_{\text{ANC}})
  = \frac{2}{m}\,\mathop{\mathrm{Var}}(\bar{Y}_{\text{post}})
    \,(1 - \rho_{\text{pre,post}}^2)
\end{equation}

\begin{orig}
where \(\rho_{\text{pre,post}}\) is the marginal
correlation between the run-in and post-randomization
means. When \(J_0 = 0\) there is no covariate and ANCOVA
reduces to the averaged estimator. When
\(\rho_{\text{pre,post}}\) is large (i.e., when
\(\sigma_b^2\) dominates \(\sigma^2\)), the \((1-\rho^2)\)
factor produces substantial variance reduction.

\end{orig}

\begin{orig}
The key advantage over GLS is that \(\phi\) is estimated
from the data rather than derived from assumed variance
components\textsuperscript{\citeproc{ref-senn2006}{1},\citeproc{ref-borm2007}{24}}. The key advantage
over the averaged estimator is that it exploits the
predictive value of the run-in observations\textsuperscript{\citeproc{ref-vanbreukelen2006}{2},\citeproc{ref-vickers2001}{25}}.

\end{orig}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{c220 }\OtherTok{\textless{}{-}} \FunctionTok{cfac}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, tt)}
\NormalTok{v\_gls }\OtherTok{\textless{}{-}} \FunctionTok{var\_gamma\_matrix}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, a, b, tt)}
\NormalTok{v\_anc }\OtherTok{\textless{}{-}} \FunctionTok{var\_gamma\_ancova}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, a, b, tt) }\SpecialCharTok{/}\NormalTok{ c220}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{v\_avg }\OtherTok{\textless{}{-}} \FunctionTok{var\_gamma\_avg}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{0}\NormalTok{, a, b, tt) }\SpecialCharTok{/}\NormalTok{ c220}\SpecialCharTok{\^{}}\DecValTok{2}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}J\_0=2, J\_1=2 (sigma\_b/sigma = 1):}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## J_0=2, J_1=2 (sigma_b/sigma = 1):
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}  GLS:    \%.4f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{, v\_gls))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   GLS:    2.1569
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}  ANCOVA: \%.4f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{, v\_anc))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ANCOVA: 2.9630
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}  Avg:    \%.4f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{, v\_avg))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Avg:    8.8889
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}  RE(GLS/ANC): \%.3f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{, v\_gls }\SpecialCharTok{/}\NormalTok{ v\_anc))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   RE(GLS/ANC): 0.728
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{\textquotesingle{}  RE(ANC/Avg): \%.3f}\SpecialCharTok{\textbackslash{}n}\StringTok{\textquotesingle{}}\NormalTok{, v\_anc }\SpecialCharTok{/}\NormalTok{ v\_avg))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   RE(ANC/Avg): 0.333
\end{verbatim}

\subsection{SUR (seemingly unrelated regression)}\label{sur-seemingly-unrelated-regression}

The SUR approach treats the run-in and treatment
periods as separate regression equations linked by
correlated errors:
\begin{align}
  Y_1 &= X_2 \begin{pmatrix}
    \beta_{11} \\ \beta_{12}
  \end{pmatrix} + e_1
  & &\text{(both groups)} \\
  Y_2 &= X_1 \alpha_2 + e_2
  & &\text{(baseline)}
\end{align}

The deviation-from-mean parameterization gives
\(\beta_1 = (\delta_1 + \delta_2)/2\) and
\(\beta_2 = (\delta_2 - \delta_1)/2\), where
\(\delta_j\) are the group-specific rates.

The SUR variance derivation and its comparison to the
GLS and averaged estimators are not developed in this
paper; the subsection is retained as a specification
only and is flagged as future work in the Discussion.

\subsection{BLUP as theoretical benchmark}\label{blup-as-theoretical-benchmark}

\begin{orig}
The three estimators above are linear functions of the
observed change scores and can be compared to a common
benchmark: the best linear unbiased predictor (BLUP) of the
individual random slopes. Under the random-slopes model with
marginal covariance \(V_i = R_i + Z_i G Z_i'\), the BLUP of the
subject-specific random slope \(b_i\) given the data is
\begin{equation}
  \hat b_i
  = G Z_i' V_i^{-1}
    \bigl(y_i - X_i \hat{\boldsymbol{\beta}}\bigr)
  \label{eq:blup}
\end{equation}
where \(\hat{\boldsymbol{\beta}}\) is the GLS estimator of the
fixed effects\textsuperscript{\citeproc{ref-henderson1975}{26},\citeproc{ref-robinson1991}{27}}.

\end{orig}

\begin{orig}
The group-specific slope estimators derived from the fixed
effects share the same variance as
\((\hat{\boldsymbol{\beta}})_\gamma\), and the GLS estimator
\(\hat\gamma_{\text{GLS}}\) minimizes the variance among all
linear unbiased estimators of \(\gamma\) when \(V_i\) is correctly
specified. The averaged and ANCOVA estimators are specific
linear approximations to this benchmark:

\end{orig}

\begin{itemize}
\tightlist
\item
  \textbf{Averaged change-score} replaces \(V_i^{-1}\) with an
  unweighted sum; this is optimal only when \(V_i \propto I\),
  which fails for any non-zero random-slope variance.
\item
  \textbf{ANCOVA} collapses the run-in visits into a single
  scalar covariate (the run-in mean) rather than weighting
  them by \(V_i^{-1}\); the resulting efficiency loss vanishes
  as \(J_0 \to \infty\) since the run-in mean becomes a
  sufficient statistic for the subject-specific intercept
  plus average slope.
\end{itemize}

\begin{orig}
Section 4 examines whether model misspecification erodes
the nominal optimality of GLS relative to these
approximations, which depend on fewer variance
components. In the \(G\) and \(R\) misspecifications studied
there, the GLS variance increases but remains below
that of the averaged estimator; whether feasible GLS with
estimated components loses its advantage in small samples
is not studied here.

\end{orig}

\section{Relative efficiency under correct specification}\label{relative-efficiency-under-correct-specification}

\subsection{Analytical comparison}\label{analytical-comparison}

The relative efficiency of the averaged estimator
to GLS is:
\begin{equation}
  \text{RE}_{\text{avg}} =
    \frac{\mathop{\mathrm{Var}}(\hat\gamma_{\text{GLS}})}
         {\mathop{\mathrm{Var}}(\hat\gamma_{\text{avg}}/c)}
    \le 1
\end{equation}
with equality when the averaged estimator happens
to coincide with GLS (which occurs in special cases).

The ordering asserted above can be stated and proved
directly. One preliminary is needed. As defined, the
averaged and ANCOVA contrasts average the accumulated
treatment effect over the post-randomization visits, so
their expectation is \(c\gamma\) rather than \(\gamma\),
where
\begin{equation}
  c = t\,\frac{J_1(J_1 + 1)/2 + J_1 J_2}{J_1 + J_2}
\end{equation}
is the mean of the accumulated-effect design column over
the post-randomization visits (\(c = 1.5t\) for the
\((2,2,0)\) design; \(c = t\) when \(J_1 = 1\), \(J_2 = 0\)).
Dividing either contrast by \(c\) yields an unbiased
estimator of \(\gamma\) with variance scaled by \(1/c^2\).

\textbf{Proposition.} Under the random-slopes model with
correctly specified \(\Sigma\),
\(\mathop{\mathrm{Var}}(\hat\gamma_{\text{GLS}}) \le
\mathop{\mathrm{Var}}(\hat\gamma_{\text{ANC}}/c) \le
\mathop{\mathrm{Var}}(\hat\gamma_{\text{avg}}/c)\).

\emph{Proof.} Each rescaled contrast is a linear unbiased
estimator of \(\gamma\), and \(\hat\gamma_{\text{GLS}}\) is
the best linear unbiased estimator of \(\gamma\) when
\(\Sigma\) is known (Gauss-Markov), which gives the first
inequality. For the second, both contrasts have the form
(post-randomization mean) \(- \phi \times\) (run-in mean):
the population ANCOVA coefficient minimizes the residual
variance over \(\phi\), while the averaged estimator fixes
\(\phi = 1\), so the ANCOVA contrast variance is no larger;
dividing both by \(c^2\) preserves the inequality. (The
feasible ANCOVA estimates \(\phi\) and carries the usual
finite-sample inflation.) \(\square\)

The ordering itself is not new.\textsuperscript{\citeproc{ref-frison1992}{5}} established
the same qualitative ranking for repeated-measures
designs with several baseline measurements, and\textsuperscript{\citeproc{ref-frison1997}{6}} extended it to repeated post-treatment
measurements; the argument above is the specialization
of that result to the run-in random-slope model, where
the run-in mean plays the role of their baseline mean.
The contribution of the following sections is the
closed-form magnitude of the two gaps as functions of
\((J_0, J_1, J_2)\) and \(\sigma_b/\sigma\), which the
Frison-Pocock parameterization does not deliver for a
slope estimand or for designs with a common close phase.

Numerically, the ordering holds with zero violations
over the 115-cell grid of the tables below. All tables,
figures, and simulation results in this paper are on the
equal-estimand \(\gamma\) scale: the averaged and ANCOVA
contrast variances are divided by \(c^2\) before any
comparison. For reference, the raw phase-mean contrasts
carry variances larger by the factor \(c^2\) (\(c^2 = 2.25\)
at the \((2,2,0)\) design), so raw-contrast comparisons
would overstate the penalty of the simpler estimators.

\begin{table}

\caption{\label{tab:re-table}RE of averaged change-score vs GLS on the $\gamma$ scale ($\mathop{\mathrm{Var}}_{\text{GLS}} / \mathop{\mathrm{Var}}(\hat\gamma_{\text{avg}}/c)$) by $\sigma_b/\sigma$.}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
$(J_0,J_1,J_2)$ & $0.5$ & $1$ & $2$ & $5$ & $20$\\
\midrule
(1,1,0) & 0.667 & 0.500 & 0.250 & 0.056 & 0.004\\
(2,1,0) & 0.653 & 0.344 & 0.117 & 0.021 & 0.001\\
(4,1,0) & 0.427 & 0.149 & 0.041 & 0.007 & 0.000\\
(0,2,0) & 0.818 & 0.900 & 0.964 & 0.994 & 1.000\\
(1,2,0) & 0.529 & 0.410 & 0.204 & 0.045 & 0.003\\
\addlinespace
(2,2,0) & 0.490 & 0.243 & 0.080 & 0.014 & 0.001\\
(4,2,0) & 0.276 & 0.089 & 0.024 & 0.004 & 0.000\\
(0,3,0) & 0.771 & 0.900 & 0.969 & 0.995 & 1.000\\
(1,3,0) & 0.501 & 0.394 & 0.193 & 0.042 & 0.003\\
(2,3,0) & 0.433 & 0.209 & 0.068 & 0.012 & 0.001\\
\addlinespace
(4,3,0) & 0.220 & 0.069 & 0.018 & 0.003 & 0.000\\
(0,1,1) & 0.727 & 0.533 & 0.245 & 0.050 & 0.003\\
(1,1,1) & 0.452 & 0.258 & 0.093 & 0.017 & 0.001\\
(2,1,1) & 0.422 & 0.181 & 0.055 & 0.009 & 0.001\\
(4,1,1) & 0.255 & 0.080 & 0.021 & 0.003 & 0.000\\
\addlinespace
(0,2,1) & 0.705 & 0.517 & 0.224 & 0.044 & 0.003\\
(1,2,1) & 0.448 & 0.262 & 0.094 & 0.017 & 0.001\\
(2,2,1) & 0.401 & 0.172 & 0.052 & 0.009 & 0.001\\
(4,2,1) & 0.221 & 0.068 & 0.018 & 0.003 & 0.000\\
(0,3,1) & 0.685 & 0.488 & 0.202 & 0.039 & 0.003\\
\addlinespace
(1,3,1) & 0.446 & 0.258 & 0.092 & 0.017 & 0.001\\
(2,3,1) & 0.380 & 0.162 & 0.049 & 0.008 & 0.001\\
(4,3,1) & 0.194 & 0.059 & 0.016 & 0.003 & 0.000\\
\bottomrule
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:re-table-anc}RE of ANCOVA vs GLS on the $\gamma$ scale ($\mathop{\mathrm{Var}}_{\text{GLS}} / \mathop{\mathrm{Var}}(\hat\gamma_{\text{ANC}}/c)$) by $\sigma_b/\sigma$.}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
$(J_0,J_1,J_2)$ & $0.5$ & $1$ & $2$ & $5$ & $20$\\
\midrule
(1,1,0) & 1.000 & 1.000 & 1.000 & 1.000 & 1.000\\
(2,1,0) & 0.971 & 0.909 & 0.860 & 0.838 & 0.834\\
(4,1,0) & 0.838 & 0.747 & 0.713 & 0.702 & 0.700\\
(0,2,0) & 0.818 & 0.900 & 0.964 & 0.994 & 1.000\\
(1,2,0) & 0.858 & 0.866 & 0.853 & 0.838 & 0.834\\
\addlinespace
(2,2,0) & 0.808 & 0.728 & 0.671 & 0.648 & 0.643\\
(4,2,0) & 0.637 & 0.544 & 0.512 & 0.502 & 0.500\\
(0,3,0) & 0.771 & 0.900 & 0.969 & 0.995 & 1.000\\
(1,3,0) & 0.808 & 0.815 & 0.785 & 0.758 & 0.751\\
(2,3,0) & 0.732 & 0.642 & 0.582 & 0.558 & 0.553\\
\addlinespace
(4,3,0) & 0.538 & 0.450 & 0.420 & 0.411 & 0.409\\
(0,1,1) & 0.727 & 0.533 & 0.245 & 0.050 & 0.003\\
(1,1,1) & 0.733 & 0.545 & 0.390 & 0.319 & 0.304\\
(2,1,1) & 0.697 & 0.542 & 0.460 & 0.430 & 0.425\\
(4,1,1) & 0.587 & 0.490 & 0.456 & 0.446 & 0.445\\
\addlinespace
(0,2,1) & 0.705 & 0.517 & 0.224 & 0.044 & 0.003\\
(1,2,1) & 0.723 & 0.541 & 0.385 & 0.313 & 0.299\\
(2,2,1) & 0.678 & 0.527 & 0.447 & 0.418 & 0.412\\
(4,2,1) & 0.539 & 0.444 & 0.413 & 0.403 & 0.401\\
(0,3,1) & 0.685 & 0.488 & 0.202 & 0.039 & 0.003\\
\addlinespace
(1,3,1) & 0.699 & 0.516 & 0.362 & 0.293 & 0.279\\
(2,3,1) & 0.642 & 0.494 & 0.416 & 0.388 & 0.382\\
(4,3,1) & 0.486 & 0.397 & 0.367 & 0.359 & 0.357\\
\bottomrule
\end{tabular}
\end{table}

\subsection{When does the gap exceed 5\%?}\label{when-does-the-gap-exceed-5}

The answer, computed over the full grid of the preceding
tables (all on the \(\gamma\) scale), is: in most cells.
Of the 115 design-by-ratio cells, 12
have ANCOVA relative efficiency of at least 0.95 (an
efficiency loss below 5\%), and they form exactly two
families. The first (6 cells) comprises
single-post-visit run-in designs with no common close
(\(J_1 = 1\), \(J_2 = 0\)): the \((1,1,0)\) design at every
tabulated ratio, plus \((2,1,0)\) at
\(\sigma_b/\sigma = 0.5\); with a single post-randomization
visit there is no within-period slope information for GLS
to exploit. The second (6 cells) comprises
designs without run-in or common close (\(J_0 = 0\),
\(J_2 = 0\), \(J_1 \in \{2, 3\}\)) at
\(\sigma_b/\sigma \ge 2\), where ANCOVA reduces to the
averaged estimator and the rescaled phase mean is nearly
efficient. In run-in designs with \(J_1 \ge 2\), the
regime that motivates this paper, the loss is
substantial: at the representative \((2,2,0)\) design the
relative efficiency ranges from
0.81 at
\(\sigma_b/\sigma = 0.5\) down to
0.64 at
\(\sigma_b/\sigma = 20\), an efficiency loss of 19\% to
36\%. The averaged estimator reaches 0.95 only in the
second family (6 of 115 cells).

\section{Robustness to misspecification}\label{robustness-to-misspecification}

\subsection{\texorpdfstring{Misspecified \(G\)}{Misspecified G}}\label{misspecified-g}

\begin{orig}
When \(\sigma_b^2\) is misestimated (e.g., too large
or too small), the GLS analysis that assumes it is no
longer optimal. Its sampling variance is then the
sandwich form
\((X'\Sigma_a^{-1}X)^{-1}
 X'\Sigma_a^{-1}\Sigma\Sigma_a^{-1}X
 (X'\Sigma_a^{-1}X)^{-1}\),
with \(\Sigma_a\) the assumed and \(\Sigma\) the true
covariance, which is the model-robust variance of\textsuperscript{\citeproc{ref-liang1986}{28}} evaluated at a known working covariance
rather than an estimated one. The averaged change-score
estimator's definition does not depend on the assumed
value, so its variance is constant across the sweep. Note the scale of
the comparison: over assumed \(\sigma_b^2 \in [0.01, 5]\)
with true \(\sigma_b^2 = 1\), the misspecified GLS
sandwich variance never exceeds 5.30, still below the
averaged-estimator variance of 8.89 on the \(\gamma\)
scale. The studied misspecification erodes but does not
overturn the GLS advantage.

\end{orig}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={(\#fig:misspec\_G)Effect of misspecifying \textbackslash sigma\_b\^{}2 on GLS variance. True \textbackslash sigma\_b\^{}2 = 1. The GLS estimator uses an assumed value on the x-axis. The averaged estimator's definition does not use \textbackslash sigma\_b\^{}2, so its \textbackslash gamma-scale variance (horizontal line) does not depend on the assumed value. The misspecified GLS variance remains below the averaged variance throughout.}]{report_files/report_files/figure-latex/misspec_G-1.pdf}}
\caption{(\#fig:misspec\_G)Effect of misspecifying \(\sigma_b^2\) on GLS variance. True \(\sigma_b^2 = 1\). The GLS estimator uses an assumed value on the x-axis. The averaged estimator's definition does not use \(\sigma_b^2\), so its \(\gamma\)-scale variance (horizontal line) does not depend on the assumed value. The misspecified GLS variance remains below the averaged variance throughout.}
\end{figure}

\subsection{\texorpdfstring{Misspecified \(R\)}{Misspecified R}}\label{misspecified-r}

\begin{orig}
When the residual correlation structure is wrong
(e.g., compound symmetry assumed but AR(1) is true),
both the GLS variance formula and the Woodbury
correction are biased. The averaged estimator's
definition does not depend on the assumed model, though
its \(\gamma\)-scale variance does change with the true
\(R\) (8.4 to 9.1 across \(\rho \in [0, 0.9]\) in the
figure). The GLS sandwich variance ranges from 0.74 to
2.16 over the same sweep, so the studied \(R\)
misspecification leaves GLS four to eleven times more
efficient than the averaged estimator throughout.

\end{orig}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={(\#fig:misspec\_R)Effect of analyzing under compound symmetry when the true correlation is AR(1). Sandwich variance of GLS (solid) vs averaged change-score on the \textbackslash gamma scale (dashed) as a function of \textbackslash rho. The averaged estimator's definition does not use the assumed correlation, but its variance varies with the true R; GLS remains at least fourfold more efficient at every \textbackslash rho.}]{report_files/report_files/figure-latex/misspec_R-1.pdf}}
\caption{(\#fig:misspec\_R)Effect of analyzing under compound symmetry when the true correlation is AR(1). Sandwich variance of GLS (solid) vs averaged change-score on the \(\gamma\) scale (dashed) as a function of \(\rho\). The averaged estimator's definition does not use the assumed correlation, but its variance varies with the true \(R\); GLS remains at least fourfold more efficient at every \(\rho\).}
\end{figure}

\section{Simulation study}\label{simulation-study}

\subsection{Design}\label{design}

\begin{orig}
To complement the analytical results, we simulate
trials under the following factorial design:

\end{orig}

\begin{itemize}
\tightlist
\item
  \(m \in \{50, 100\}\) per group
\item
  \((J_0, J_1, J_2) \in \{(0,2,0), (2,2,0), (2,2,2)\}\)
\item
  \(\sigma_b/\sigma \in \{1, 5\}\)
\item
  True correlation: compound symmetry (an AR(1) truth
  is examined analytically in Section 4 but is not
  simulated)
\item
  Analysis: GLS (correctly specified), GLS
  (misspecified), averaged change-score
\end{itemize}

\begin{orig}
For each configuration, 1000 trials are simulated. The
outcomes are the empirical standard deviation of
\(\hat\gamma\) and the empirical power. Coverage of
nominal 95\% confidence intervals and empirical size at
\(\Delta = 0\) are not assessed; extending the factorial
to \(m \in \{30, 200\}\), \(\sigma_b/\sigma = 20\), an
AR(1) truth arm, and 5000 replicates remains future
work. Test statistics use standard normal critical
values rather than \(t\); the distinction is immaterial
at \(m \ge 50\) per group.

\end{orig}

\subsection{Results}\label{results}

\begin{orig}
We simulate the factorial design described above under
compound symmetry, comparing the correctly specified GLS
estimator, a GLS estimator that misstates the random-slope
variance (it assumes \(\sigma_b^2 = \sigma^2\) regardless of the
truth), and the averaged change-score estimator, the latter
rescaled to the \(\gamma\) scale by dividing the contrast by
\(c\). For each cell we report the empirical standard deviation
of \(\hat\gamma\) and the empirical power from 1000 replicates;
the Monte Carlo standard error of a tabulated power estimate
is at most \(\sqrt{0.25/1000} \approx 0.016\).

\end{orig}

\begin{table}

\caption{\label{tab:simulation-study}Monte Carlo comparison of GLS (correctly specified), GLS (misspecified $\sigma_b^2$, assuming $\sigma_b^2=\sigma^2$), and the averaged change-score estimator under compound symmetry (1000 replicates, $\Delta=0.5$, two-sided $\alpha=0.05$). Columns report the empirical standard deviation of $\hat\gamma$ and the empirical power. The averaged estimator is rescaled to the $\gamma$ scale (contrast divided by $c$).}
\centering
\begin{tabular}[t]{lrrrrrrrr}
\toprule
Design & $\sigma_b/\sigma$ & $m$ & SD GLS & SD mis & SD avg & Pow GLS & Pow mis & Pow avg\\
\midrule
(0,2,0) & 1 & 50 & 0.238 & 0.238 & 0.250 & 0.537 & 0.537 & 0.495\\
(2,2,0) & 1 & 50 & 0.210 & 0.210 & 0.417 & 0.677 & 0.677 & 0.206\\
(2,2,2) & 1 & 50 & 0.151 & 0.151 & 0.458 & 0.902 & 0.902 & 0.192\\
(0,2,0) & 1 & 100 & 0.169 & 0.169 & 0.178 & 0.823 & 0.823 & 0.769\\
(2,2,0) & 1 & 100 & 0.146 & 0.146 & 0.308 & 0.926 & 0.926 & 0.393\\
\addlinespace
(2,2,2) & 1 & 100 & 0.108 & 0.108 & 0.334 & 0.997 & 0.997 & 0.345\\
(0,2,0) & 5 & 50 & 1.012 & 1.012 & 1.017 & 0.083 & 0.653 & 0.083\\
(2,2,0) & 5 & 50 & 0.241 & 0.528 & 2.043 & 0.555 & 0.600 & 0.067\\
(2,2,2) & 5 & 50 & 0.164 & 0.284 & 2.297 & 0.873 & 0.765 & 0.054\\
(0,2,0) & 5 & 100 & 0.726 & 0.726 & 0.726 & 0.108 & 0.733 & 0.109\\
\addlinespace
(2,2,0) & 5 & 100 & 0.162 & 0.360 & 1.387 & 0.857 & 0.748 & 0.067\\
(2,2,2) & 5 & 100 & 0.106 & 0.189 & 1.573 & 0.997 & 0.936 & 0.060\\
\bottomrule
\end{tabular}
\end{table}

One feature of the table requires comment. In the
\((0,2,0)\) rows the correctly specified and misspecified
GLS analyses report identical empirical standard
deviations but different powers. With \(J_0 = 0\) the
design has two observations and two fixed effects, so
the GLS point estimator does not depend on the assumed
covariance and the two analyses coincide as estimators;
the apparent power advantage of the misspecified
analysis reflects only an anticonservative model-based
standard error, not additional information. More
generally, because empirical size at \(\Delta = 0\) and
interval coverage are not tabulated, power comparisons
across variance models in this table are not
interpretable as efficiency comparisons; adding size and
coverage columns is remaining work.

\section{Numerical examples}\label{numerical-examples}

\subsection{MIRIAD parameters}\label{miriad-parameters}

\begin{table}

\caption{\label{tab:miriad-comparison}Sample size per group: GLS, ANCOVA, and averaged estimators (MIRIAD parameters, $\Delta=0.25$, 90\% power). All variances are on the $\gamma$ scale (ANCOVA and averaged contrasts divided by $c$).}
\centering
\begin{tabular}[t]{lrrr}
\toprule
$(J_0,J_1,J_2)$ & $N$ GLS & $N$ ANC & $N$ Avg\\
\midrule
(4,3,1) & 36 & 95 & 1630\\
(4,3,0) & 43 & 100 & 1676\\
(4,2,1) & 60 & 144 & 2413\\
(2,3,1) & 69 & 162 & 1053\\
(4,2,0) & 78 & 151 & 2368\\
\addlinespace
(2,3,0) & 93 & 157 & 1028\\
(1,3,1) & 99 & 255 & 821\\
(2,2,1) & 104 & 226 & 1479\\
(0,3,1) & 112 & 433 & 433\\
(1,2,1) & 138 & 335 & 1116\\
\addlinespace
(2,2,0) & 145 & 213 & 1361\\
(0,2,1) & 150 & 527 & 527\\
(4,1,1) & 156 & 339 & 5328\\
(1,3,0) & 185 & 233 & 775\\
(2,1,1) & 226 & 478 & 3063\\
\bottomrule
\end{tabular}
\end{table}

\subsection{When to use which estimator}\label{when-to-use-which-estimator}

A decision rule based on \(m\), \(\sigma_b/\sigma\), and
confidence in the correlation structure requires the
feasible-GLS simulation described in the Discussion and
is deferred to a revision. The results above support
only the narrower statement that, with variance
components taken as known, GLS dominates and the
penalty of the simpler estimators is largest in run-in
designs with \(J_1 \ge 2\) and high \(\sigma_b/\sigma\).

\section{Discussion}\label{discussion}

\begin{orig}
The estimator comparison yields a graded recommendation rather
than a single winner. Under correct specification GLS is
efficient and dominates both ANCOVA and the averaged
change-score estimator, as the ordering
\(\mathop{\mathrm{Var}}_{\text{GLS}} \le \mathop{\mathrm{Var}}_{\text{ANC}} \le
\mathop{\mathrm{Var}}_{\text{avg}}\) confirms. This dominance is a large-sample
statement: it presumes the covariance components are known or
well estimated. With moderate-to-large samples and a credible
covariance model, GLS is the appropriate default.

\end{orig}

\begin{orig}
The misspecification analysis qualifies the case for GLS less
than might be expected. Because GLS weights the data by an
assumed inverse covariance, errors in the assumed \(G\) or \(R\)
feed into its sampling variance, and the sandwich-variance
calculations quantify the inflation. In the settings studied,
however, the inflation never closes the gap: the misspecified
GLS variance peaks at 5.30 in the \(G\) sweep and at 2.16 in the
\(R\) sweep, against \(\gamma\)-scale averaged-estimator variances
of 8.4 to 9.1 at the same design. The averaged change-score
estimator avoids the
variance components entirely, and ANCOVA estimates the run-in
coefficient from the data, but under the misspecifications
examined neither robustness property is enough to overcome
their efficiency deficit. These calculations take the variance
components of the GLS analysis as fixed inputs; the open and
practically important question is whether feasible GLS, with
components estimated by REML from small samples, keeps its
advantage. That question is not answered here.

\end{orig}

\begin{orig}
The practical importance of the estimator choice depends on the
design. As the numbers of run-in and treatment observations
grow, the phase means approach sufficiency for the
subject-specific slope, the ANCOVA efficiency loss vanishes as
\(J_0 \to \infty\), and the relative efficiencies of all three
estimators converge toward one. The gap is largest, and the
choice of estimator therefore most consequential, in small
designs with few observations per phase and a high
slope-to-noise ratio, exactly the regime in which the
estimated covariance is also least stable. Whether that
instability erodes the feasible-GLS advantage enough to
change the ranking in small studies is the question the
planned feasible-GLS simulation must answer; the
known-components results here cannot.

\end{orig}

\begin{orig}
Two estimators not fully developed here would round out the
comparison. The seemingly unrelated regression formulation of
Section 2.4 treats the run-in and treatment periods as linked
equations and offers a compromise between the averaged
estimator and full GLS, at the cost of additional
implementation complexity; its variance derivation remains to
be completed. The constrained longitudinal data analysis
estimator uses the full covariance without committing to a
random-effects distribution and should fall between ANCOVA
and GLS in efficiency. A comprehensive treatment would compare
all of these under a feasible-GLS simulation in which the
variance components are estimated rather than assumed, which is
the setting in which the robustness distinctions drawn here
become decisive.

\end{orig}

\section{Conflict of interest}\label{conflict-of-interest}

The author declares no conflicts of interest.

\section{Funding}\label{funding}

This work received no specific funding.

\section{Data availability statement}\label{data-availability-statement}

\begin{orig}
The \texttt{runinpower} R package implementing the GLS, ANCOVA, and
averaged-change-score estimators (\texttt{ancova.R}, \texttt{averaged.R}),
the simulation drivers, and the shared bibliography across the
four-paper compendium are openly available in the project
repository. Specific paths are listed in the Reproducibility
section below.

\end{orig}

\section{Reproducibility}\label{reproducibility}

\begin{orig}
This manuscript was rendered with R 4.4.x. Principal packages
used are the in-package \texttt{runinpower} source, \texttt{tinytest}
(testing harness), and \texttt{rmarkdown} plus \texttt{bookdown} for the
manuscript build. The GLS comparator in the simulation is
implemented directly in the manuscript source
(\texttt{analyze\_gls} in the simulation chunk); no external mixed
model fitter is used.

\end{orig}

\begin{orig}
\textbf{Random-number generator.} The Monte Carlo simulation
comparing the three estimators sets \texttt{set.seed(20260418)} once,
immediately before the replicate loop. No per-replicate
reseeding is performed, so the full replicate stream, and
hence the tabulated results, follow deterministically from
that single seed.

\end{orig}

\begin{orig}
\textbf{Data and code availability.} The R package source is at
\texttt{R/}. Simulation drivers are at \texttt{analysis/scripts/}. The
companion manuscripts (Papers 1, 2, 3) are at
\texttt{analysis/report/\{01,02,03\}-*/}. The manuscript source and
shared bibliography (\texttt{references.bib}, a symlink to
\texttt{../../references.bib}) are at
\texttt{analysis/report/04-gls-vs-ttest/}.

\end{orig}

\section{References}\label{references}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{0}{1}
\bibitem[\citeproctext]{ref-senn2006}
\CSLLeftMargin{1. }%
\CSLRightInline{Senn S. Change from baseline and analysis of covariance revisited. \emph{Statistics in Medicine}. 2006;25(24):4334-4344. doi:\href{https://doi.org/10.1002/sim.2682}{10.1002/sim.2682}}

\bibitem[\citeproctext]{ref-vanbreukelen2006}
\CSLLeftMargin{2. }%
\CSLRightInline{Van Breukelen GJP. {ANCOVA} versus change from baseline had more power in randomized studies and more bias in nonrandomized studies. \emph{Journal of Clinical Epidemiology}. 2006;59(9):920-925. doi:\href{https://doi.org/10.1016/j.jclinepi.2006.02.007}{10.1016/j.jclinepi.2006.02.007}}

\bibitem[\citeproctext]{ref-crager1987}
\CSLLeftMargin{3. }%
\CSLRightInline{Crager MR. Analysis of covariance in parallel-group clinical trials with pretreatment baselines. \emph{Biometrics}. 1987;43(4):895-901. doi:\href{https://doi.org/10.2307/2531542}{10.2307/2531542}}

\bibitem[\citeproctext]{ref-yang2001}
\CSLLeftMargin{4. }%
\CSLRightInline{Yang L, Tsiatis AA. Efficiency study of estimators for a treatment effect in a pretest-posttest trial. \emph{The American Statistician}. 2001;55(4):314-321. doi:\href{https://doi.org/10.1198/000313001753272466}{10.1198/000313001753272466}}

\bibitem[\citeproctext]{ref-frison1992}
\CSLLeftMargin{5. }%
\CSLRightInline{Frison L, Pocock SJ. Repeated measures in clinical trials: Analysis using mean summary statistics and its implications for design. \emph{Statistics in Medicine}. 1992;11(13):1685-1704. doi:\href{https://doi.org/10.1002/sim.4780111304}{10.1002/sim.4780111304}}

\bibitem[\citeproctext]{ref-frison1997}
\CSLLeftMargin{6. }%
\CSLRightInline{Frison L, Pocock SJ. Linearly divergent treatment effects in clinical trials with repeated measures: Efficient analysis using summary statistics. \emph{Statistics in Medicine}. 1997;16(24):2855-2872. doi:\href{https://doi.org/10.1002/(SICI)1097-0258(19971230)16:24\%3C2855::AID-SIM749\%3E3.0.CO;2-2}{10.1002/(SICI)1097-0258(19971230)16:24\textless2855::AID-SIM749\textgreater3.0.CO;2-2}}

\bibitem[\citeproctext]{ref-hu2021}
\CSLLeftMargin{7. }%
\CSLRightInline{Hu N, Mackey H, Thomas R. Power and sample size for random coefficient regression models in randomized experiments with monotone missing data. \emph{Biometrical Journal}. 2021;63(4):806-824. doi:\href{https://doi.org/10.1002/bimj.202000184}{10.1002/bimj.202000184}}

\bibitem[\citeproctext]{ref-liu2009}
\CSLLeftMargin{8. }%
\CSLRightInline{Liu GF, Lu K, Mogg R, Mallick M, Mehrotra DV. Should baseline be a covariate or dependent variable in analyses of change from baseline in clinical trials? \emph{Statistics in Medicine}. 2009;28(20):2509-2530. doi:\href{https://doi.org/10.1002/sim.3639}{10.1002/sim.3639}}

\bibitem[\citeproctext]{ref-lu2010}
\CSLLeftMargin{9. }%
\CSLRightInline{Lu K. On efficiency of constrained longitudinal data analysis versus longitudinal analysis of covariance. \emph{Biometrics}. 2010;66(3):891-896. doi:\href{https://doi.org/10.1111/j.1541-0420.2009.01322.x}{10.1111/j.1541-0420.2009.01322.x}}

\bibitem[\citeproctext]{ref-tsiatis2008}
\CSLLeftMargin{10. }%
\CSLRightInline{Tsiatis AA, Davidian M, Zhang M, Lu X. Covariate adjustment for two-sample treatment comparisons in randomized clinical trials: A principled yet flexible approach. \emph{Statistics in Medicine}. 2008;27(23):4658-4677. doi:\href{https://doi.org/10.1002/sim.3113}{10.1002/sim.3113}}

\bibitem[\citeproctext]{ref-mallinckrodt2021}
\CSLLeftMargin{11. }%
\CSLRightInline{{Mallinckrodt CH, Ye J, et al.} Mixed models for repeated measures should include time-by-covariate interactions to assure power gains and robustness against dropout bias relative to complete-case {ANCOVA}. \emph{Statistics in Biopharmaceutical Research}. Published online 2021. doi:\href{https://doi.org/10.1080/19466315.2021.1976846}{10.1080/19466315.2021.1976846}}

\bibitem[\citeproctext]{ref-brogan1980}
\CSLLeftMargin{12. }%
\CSLRightInline{Brogan DR, Kutner MH. Comparative analyses of pretest-posttest research designs. \emph{The American Statistician}. 1980;34(4):229-232. doi:\href{https://doi.org/10.1080/00031305.1980.10483034}{10.1080/00031305.1980.10483034}}

\bibitem[\citeproctext]{ref-coffman2016}
\CSLLeftMargin{13. }%
\CSLRightInline{Coffman CJ, Edelman D, Woolson RF. To condition or not condition? {Analysing} {``change''} in longitudinal randomised controlled trials. \emph{BMJ Open}. 2016;6(12):e013096. doi:\href{https://doi.org/10.1136/bmjopen-2016-013096}{10.1136/bmjopen-2016-013096}}

\bibitem[\citeproctext]{ref-wang2019}
\CSLLeftMargin{14. }%
\CSLRightInline{Wang G, Aschenbrenner AJ, Li Y, et al. Two-period linear mixed effects models to analyze clinical trials with run-in data when the primary outcome is continuous: {Applications} to {Alzheimer's} disease. \emph{Alzheimer's \& Dementia: Translational Research \& Clinical Interventions}. 2019;5:450-457. doi:\href{https://doi.org/10.1016/j.trci.2019.08.002}{10.1016/j.trci.2019.08.002}}

\bibitem[\citeproctext]{ref-liang2000}
\CSLLeftMargin{15. }%
\CSLRightInline{Liang KY, Zeger SL. Longitudinal data analysis of continuous and discrete responses for pre-post designs. \emph{Sankhya: The Indian Journal of Statistics, Series B}. 2000;62(1):134-148.}

\bibitem[\citeproctext]{ref-funatogawa2020}
\CSLLeftMargin{16. }%
\CSLRightInline{Funatogawa I, Funatogawa T. Longitudinal analysis of pre- and post-treatment measurements with equal baseline assumptions in randomized trials. \emph{Biometrical Journal}. 2020;62(5):1235-1249. doi:\href{https://doi.org/10.1002/bimj.201800389}{10.1002/bimj.201800389}}

\bibitem[\citeproctext]{ref-iddi2022}
\CSLLeftMargin{17. }%
\CSLRightInline{Iddi S, Donohue MC. Power and sample size for longitudinal models in {R} -- the longpower package and {Shiny} app. \emph{The R Journal}. 2022;14(1):264-282. \url{https://journal.r-project.org/articles/RJ-2022-022/}}

\bibitem[\citeproctext]{ref-liuliang1997}
\CSLLeftMargin{18. }%
\CSLRightInline{Liu G, Liang KY. Sample size calculations for studies with correlated observations. \emph{Biometrics}. 1997;53:937-947. doi:\href{https://doi.org/10.2307/2533554}{10.2307/2533554}}

\bibitem[\citeproctext]{ref-diggle2002}
\CSLLeftMargin{19. }%
\CSLRightInline{Diggle PJ, Heagerty P, Liang KY, Zeger SL. \emph{Analysis of Longitudinal Data}. 2nd ed. Oxford University Press; 2002.}

\bibitem[\citeproctext]{ref-ard2011}
\CSLLeftMargin{20. }%
\CSLRightInline{Ard MC, Edland SD. Power calculations for clinical trials in {Alzheimer's} disease. \emph{Journal of Alzheimer's Disease}. 2011;21:369-377. doi:\href{https://doi.org/10.3233/JAD-2011-0062}{10.3233/JAD-2011-0062}}

\bibitem[\citeproctext]{ref-frost2008}
\CSLLeftMargin{21. }%
\CSLRightInline{Frost C, Kenward MG, Fox NC. Optimizing the design of clinical trials where the outcome is a rate. {Can} estimating a baseline rate in a run-in period increase efficiency? \emph{Statistics in Medicine}. 2008;27(18):3717-3731. doi:\href{https://doi.org/10.1002/sim.3280}{10.1002/sim.3280}}

\bibitem[\citeproctext]{ref-laird1982}
\CSLLeftMargin{22. }%
\CSLRightInline{Laird NM, Ware JH. Random-effects models for longitudinal data. \emph{Biometrics}. 1982;38(4):963-974. doi:\href{https://doi.org/10.2307/2529876}{10.2307/2529876}}

\bibitem[\citeproctext]{ref-verbeke2000}
\CSLLeftMargin{23. }%
\CSLRightInline{Verbeke G, Molenberghs G. \emph{Linear Mixed Models for Longitudinal Data}. Springer; 2000.}

\bibitem[\citeproctext]{ref-borm2007}
\CSLLeftMargin{24. }%
\CSLRightInline{Borm GF, Fransen J, Lemmens WAJG. A simple sample size formula for analysis of covariance in randomized clinical trials. \emph{Journal of Clinical Epidemiology}. 2007;60(12):1234-1238. doi:\href{https://doi.org/10.1016/j.jclinepi.2007.02.006}{10.1016/j.jclinepi.2007.02.006}}

\bibitem[\citeproctext]{ref-vickers2001}
\CSLLeftMargin{25. }%
\CSLRightInline{Vickers AJ. The use of percentage change from baseline as an outcome in a controlled trial is statistically inefficient: A simulation study. \emph{BMC Medical Research Methodology}. 2001;1:6. doi:\href{https://doi.org/10.1186/1471-2288-1-6}{10.1186/1471-2288-1-6}}

\bibitem[\citeproctext]{ref-henderson1975}
\CSLLeftMargin{26. }%
\CSLRightInline{Henderson CR. Best linear unbiased estimation and prediction under a selection model. \emph{Biometrics}. 1975;31(2):423-447. doi:\href{https://doi.org/10.2307/2529430}{10.2307/2529430}}

\bibitem[\citeproctext]{ref-robinson1991}
\CSLLeftMargin{27. }%
\CSLRightInline{Robinson GK. That {BLUP} is a good thing: The estimation of random effects. \emph{Statistical Science}. 1991;6(1):15-32. doi:\href{https://doi.org/10.1214/ss/1177011926}{10.1214/ss/1177011926}}

\bibitem[\citeproctext]{ref-liang1986}
\CSLLeftMargin{28. }%
\CSLRightInline{Liang KY, Zeger SL. Longitudinal data analysis using generalized linear models. \emph{Biometrika}. 1986;73(1):13-22. doi:\href{https://doi.org/10.1093/biomet/73.1.13}{10.1093/biomet/73.1.13}}

\end{CSLReferences}

\end{document}
