% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[left=3cm,right=3cm,top=2.5cm,bottom=2.5cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{caption}
\captionsetup[table]{skip=6pt}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
% Paragraph scaffolding for manuscript revision.
%
% Two environments, presented in this order per paragraph:
%
%   rgt   -- author's rewrite (initially a placeholder)
%            small, italic, dark blue
%   orig  -- original Claude-authored draft, and until the rewrite
%            replaces it, the body text of the manuscript
%            normal size, gray
%
% The `bullets' environment (a boiled-down topic sentence plus bullet
% points, one per paragraph) is no longer used inside manuscripts:
% those blocks now live in a companion bullets.Rmd supplement in the
% same report directory, which typesets them as plain \textbf{} +
% itemize and needs no part of this file. The definition is retained
% only so that a stray block left in a document still compiles.
%
% This file is identical across every manuscript that includes it.
% It previously existed in two variants that swapped the sizes of
% rgt and orig, so the same markup rendered differently depending on
% which repository the manuscript lived in. The variant retained here
% keeps orig at full size because orig, not rgt, currently carries
% the prose in every manuscript in the pool.

\usepackage{xcolor}

\newcounter{pgraph}

\newenvironment{bullets}{%
  \stepcounter{pgraph}%
  \begin{quote}\small\sffamily\color[gray]{0.30}%
  {\normalfont\scriptsize\color[gray]{0.58}[\thepgraph]\enspace}}{%
  \end{quote}}

\newenvironment{rgt}{%
  \begin{quote}\small\itshape\color[RGB]{20,60,160}}{%
  \end{quote}}

\newenvironment{orig}{%
  \begin{quote}\normalsize\color[gray]{0.55}}{%
  \end{quote}}

% backward compat alias
\newenvironment{claudecode}{\begin{orig}}{\end{orig}}
%% tools/stamp.tex
%% Provenance footer for PDFs rendered from this project.
%% Vendored by zzcollab; this file is not project-specific. The
%% footer prints the source document and the time of rendering.
%% The git version is defined here too, and so is available to a
%% project that wants it on the page, but it is left off the
%% default footer: it already names the staged copy in share/ and
%% appears in its manifest row. All values are supplied at render
%% time by tools/stamp-render.R, which writes a small generated
%% file that redefines the macros below. The \providecommand
%% defaults keep a bare LaTeX compile working when the document is
%% built without the wrapper.
\usepackage{fancyhdr}
\usepackage{xcolor}
\providecommand{\stampsource}{\detokenize{(source not recorded)}}
\providecommand{\stamptime}{(time not recorded)}
\providecommand{\stampversion}{\detokenize{(version not recorded)}}
\setlength{\footskip}{40pt}
\newcommand{\stampfootcontent}{%
  \footnotesize\color{gray}%
  \parbox[b]{\textwidth}{%
    \stamptime\hfill\thepage\\[2pt]%
    \ttfamily\raggedright\stampsource}}
\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\stampfootcontent}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}
%% The title page uses the `plain` page style; redefine it so the
%% stamp appears there too.
\fancypagestyle{plain}{%
  \fancyhf{}%
  \fancyfoot[C]{\stampfootcontent}%
  \renewcommand{\headrulewidth}{0pt}%
  \renewcommand{\footrulewidth}{0.4pt}}
\renewcommand{\stampsource}{\textasciitilde{}/\allowbreak{}prj/\allowbreak{}res/\allowbreak{}04-runin-power-analysis/\allowbreak{}runinpower/\allowbreak{}analysis/\allowbreak{}report/\allowbreak{}02-correlation/\allowbreak{}report.Rmd}
\renewcommand{\stamptime}{2026-08-15 16:07 PDT}
\renewcommand{\stampversion}{\detokenize{455c889-wip}}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{float}
\usepackage[mathlines]{lineno}
\linenumbers
\DeclareMathOperator{\Var}{Var}
\DeclareMathOperator{\Cov}{Cov}
\DeclareMathOperator{\Corr}{Corr}
\DeclareMathOperator{\tr}{tr}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
% fallback for those not using the hyperref driver hyperxmp:
\makeatletter
\@ifundefined{xmpquote}{\newcommand{\xmpquote}[1]{#1}}{}
\makeatother
\hypersetup{
  pdftitle={Power Analysis for Run-In Clinical Trials under AR(1) and General Correlation Structures},
  pdfauthor={Ronald G. Thomas, Ph.D.},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Power Analysis for Run-In Clinical Trials under
AR(1) and General Correlation Structures}
\author{Ronald G. Thomas, Ph.D.\thanks{Wertheim School of Public Health, UCSD; ORCID: 0000-0003-1686-4965}}
\date{August 15, 2026}

\begin{document}
\maketitle
\begin{abstract}
\textbf{Background.} The companion Paper 1 of this compendium
derived closed-form power formulas for run-in and common
close observations under compound symmetry. Compound
symmetry assumes all pairs of observations are equally
correlated regardless of temporal separation, an assumption
that is empirically rejected in most longitudinal-trial data.
AR(1), \(\Corr(Y_{ijk}, Y_{ijk'}) = \rho^{|k-k'|}\), is the
natural alternative.
\textbf{Methods.} We derive the variance of the treatment-effect
estimator under AR(1) via two routes: (i) the Woodbury
identity applied to the AR(1) marginal covariance, and (ii)
a moment-based approach using the cross-covariance between
run-in and treatment-period means. The two routes target
different estimands: the GLS variance of the slope-difference
effect and the variance of the simple phase-mean difference.
The GLS derivation accommodates arbitrary \(J_0\) run-in
observations and arbitrary \(J_2\) common close observations.
\textbf{Results.} A taxonomy of five correlation cases is
presented, and change-score correlations are derived in
closed form under compound symmetry and AR(1). Numerical
comparisons using parameters from Alzheimer's disease
neuroimaging trials show that, when the two structures are
matched at a common nominal correlation parameter \(\rho\),
the AR(1) sample-size estimate is smaller than the
compound-symmetric estimate (by 4-36\% at \(\rho = 0.5\)),
with the deviation growing as \(\rho\) increases. A narrow
anticonservative regime exists at large \(J_0\) and small
\(\rho\), where compound symmetry understates the variance
by at most about 6\%.
\textbf{Conclusions.} At a matched nominal \(\rho\), the
compound-symmetry assumption underlying Paper 1 is generally
conservative: it overstates the required sample size, and
increasingly so as the autocorrelation grows. The exception
is a narrow regime with many run-in observations and low
autocorrelation, where it is anticonservative by at most
about 6\%. The AR(1) formulas derived here quantify both
effects and should be used directly when serial correlation
is expected; this conclusion is specific to the
common-nominal-\(\rho\) matching convention stated in the
text.
\end{abstract}

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\setstretch{1.1}
\section{Introduction}\label{introduction}

\begin{orig}
The efficiency of run-in designs depends on the
correlation structure of the repeated measurements.
Under compound symmetry, the correlation between any
two change scores is constant, and the run-in
observations contribute information about the random
slope \(b_i\) through a simple averaging mechanism. Under
AR(1), the correlation decays with temporal separation,
and the information content of run-in observations
depends on how far they are from the treatment period.

\end{orig}

\begin{orig}
Paper 1\textsuperscript{\citeproc{ref-frost2008}{1}} assumed \(R = \sigma^2(I_J +
\mathbf{1}_J\mathbf{1}_J')\), which arises from the
change-score parameterization under independent errors.\textsuperscript{\citeproc{ref-wang2019}{2}} extended the run-in framework to two-period
linear mixed models but retained the compound symmetry
assumption. We extend here to AR(1) residual
correlation, where \(\mathop{\mathrm{Corr}}(e_{ij}, e_{ij'}) =
\rho^{|j-j'|}\) for \(0 < \rho < 1\).

\end{orig}

\begin{orig}
\textsuperscript{\citeproc{ref-winkens2007}{3}} studied optimal designs for autocorrelated
longitudinal data but did not consider the run-in
setting.\textsuperscript{\citeproc{ref-diggle2002}{4}} and\textsuperscript{\citeproc{ref-verbeke2000}{5}} provide general
treatments of correlation structures in longitudinal
models.\textsuperscript{\citeproc{ref-munoz1992}{6}} proposed a damped-exponential family
of correlation structures with \(\mathop{\mathrm{Corr}}(e_{ij}, e_{ij'}) =
\rho^{|j-j'|^{\theta}}\), which contains compound symmetry
(\(\theta = 0\)) and AR(1) (\(\theta = 1\)) as the two
boundary members; the comparison developed here is thus a
comparison of the two ends of that family, and the
intermediate members offer a route to relaxing the binary
choice.\textsuperscript{\citeproc{ref-chambless1993}{7}} addressed the effect of
intra-individual variation on change-score analyses,
a concern that is amplified under AR(1) correlation.

\end{orig}

\begin{orig}
The \texttt{longpower} R package\textsuperscript{\citeproc{ref-iddi2022}{8}} is the CRAN
reference implementation for longitudinal-trial power
calculations. Its \texttt{power.mmrm.ar1()} routine implements
the analytic AR(1) sample-size formula of\textsuperscript{\citeproc{ref-lu2008}{9}} for
mixed models for repeated measures, and its slope-based
closed-form routines (\texttt{edland.linear.power()},
\texttt{diggle.linear.power()}) assume random intercepts and
slopes with independent or compound-symmetric residuals.
None of these routines accommodates run-in or common
close observations under a random-slope model. The
closed-form AR(1) derivation developed here supplies
that case. As \(\rho \to 0\) (no serial correlation), the
AR(1) change-score covariance collapses to the
compound-symmetric structure of Paper 1, so the present
formulas contain the Paper 1 results as a special case.

\end{orig}

\section{Correlation structures for longitudinal trials}\label{correlation-structures-for-longitudinal-trials}

\subsection{Taxonomy of cases}\label{taxonomy-of-cases}

We consider five correlation structures for the
raw outcomes \(Y_{ijk}\):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Compound symmetry:}
  \(\mathop{\mathrm{Corr}}(Y_{ijk}, Y_{ijk'}) = \rho\) for all
  \(k \ne k'\). This is equivalent to the random
  intercept model and produces the \(R = \sigma^2(I +
  \mathbf{1}\mathbf{1}')\) structure in change scores.
\item
  \textbf{AR(1):}
  \(\mathop{\mathrm{Corr}}(Y_{ijk}, Y_{ijk'}) = \rho^{|k'-k|}\).
  Correlation decays geometrically with lag.
\item
  \textbf{Compound symmetry with variable run-in:}
  Case 1 with \(J_{0,i}\) varying across participants.
\item
  \textbf{AR(1) with variable run-in and common close:}
  Case 2 with \(J_{0,i}\) and \(J_{2,i}\) varying.
\item
  \textbf{General (unstructured):}
  \(\mathop{\mathrm{Corr}}(Y_{ijk}, Y_{ijk'}) = \sigma_{|k-k'|}/\sigma^2\).
\end{enumerate}

Throughout, the design quantities \(J_0\), \(J_1\), and
\(J_2\) correspond to the arguments \texttt{r}, \texttt{k}, and \texttt{f} of
the implementing \texttt{runinpower} functions.

\subsection{Change-score correlations under each structure}\label{change-score-correlations-under-each-structure}

Under the consecutive-difference parameterization
(\(C_j = Y_j - Y_{j-1}\), successive visits separated by
\(t\)), the correlation between change scores depends on
the raw-outcome correlation structure. Here
\(a = \sigma^2\) and \(b = \sigma_b^2\). (The GLS machinery
of the next section uses change scores from baseline;
the two parameterizations are related by a nonsingular
linear map, so the GLS variance is unaffected.)

For the run-in design with \(J_0 = 2\), \(J_1 = 1\), with
visits at times \(-2t, -t, 0, t\) and consecutive
differences \(C_1, C_2, C_3\):

\textbf{Compound symmetry (independent raw errors; the shared
intercept component cancels in differencing):}
\begin{align}
  \mathop{\mathrm{Corr}}(C_1, C_3) &= \frac{bt^2}{2a + bt^2} \\
  \mathop{\mathrm{Corr}}(C_1, C_2) &= \frac{-a + bt^2}{2a + bt^2}
\end{align}

\textbf{AR(1):} for consecutive differences at lag
\(m = |j - l| \ge 1\),
\begin{align}
  \mathop{\mathrm{Var}}(C_j) &= bt^2 + 2a(1 - \rho) \\
  \mathop{\mathrm{Cov}}(C_j, C_l) &= bt^2 - a\,\rho^{m-1}(1 - \rho)^2
\end{align}
so that
\begin{align}
  \mathop{\mathrm{Corr}}(C_1, C_3) &=
    \frac{bt^2 - a\rho(1 - \rho)^2}
         {bt^2 + 2a(1 - \rho)} \\
  \mathop{\mathrm{Corr}}(C_1, C_2) &=
    \frac{bt^2 - a(1 - \rho)^2}
         {bt^2 + 2a(1 - \rho)}
\end{align}
These expressions hold for arbitrary \((J_0, J_1, J_2)\)
because they depend only on the lag \(m\); at \(\rho = 0\)
they reduce to the compound-symmetry formulas above.

\section{Variance under AR(1): GLS approach}\label{variance-under-ar1-gls-approach}

\subsection{Marginal covariance}\label{marginal-covariance}

Under AR(1) with residual variance \(\sigma^2\) and
autocorrelation \(\rho\), the raw-outcome covariance is
\(\mathop{\mathrm{Cov}}(e_{ij}, e_{ij'}) = \sigma^2 \rho^{|j-j'|}\).
The change-score residual covariance becomes:
\begin{equation}
  R_{jl} = \mathop{\mathrm{Cov}}(e_{ij} - e_{i0}, e_{il} - e_{i0})
  = \sigma^2(\rho^{|j-l|} - \rho^{|j|} - \rho^{|l|} + 1)
\end{equation}
for \(j, l \ne 0\).

\begin{orig}
This \(R\) no longer has the rank-one-plus-identity
structure, so the Sherman-Morrison formula does not
apply. However, the Woodbury identity still reduces
\(\Sigma^{-1}\) to a scalar inversion because \(G\) remains
scalar.

\end{orig}

\subsection{Woodbury computation}\label{woodbury-computation}

The computation proceeds identically to Paper 1:
\begin{equation}
  \Sigma^{-1} = R^{-1} - R^{-1}Z
    (G^{-1} + Z'R^{-1}Z)^{-1} Z'R^{-1}
\end{equation}

\begin{orig}
with \(H = (G^{-1} + Z'R^{-1}Z)^{-1}\) still scalar.
The difference is that \(R^{-1}\) must be computed
numerically (or via the AR(1) tridiagonal inverse)
rather than by Sherman-Morrison.

\end{orig}

\begin{table}

\caption{\label{tab:ar1-variance}Per-pair $\mathop{\mathrm{Var}}(\hat\gamma)$ under AR(1) for varying $\rho$ ($J_1=2$, $J_2=0$, $\sigma^2=1$, $\sigma_b^2=1$).}
\centering
\begin{tabular}[t]{rrrrrr}
\toprule
$J_0$ & $\rho=0$ & $\rho=0.3$ & $\rho=0.5$ & $\rho=0.7$ & $\rho=0.9$\\
\midrule
0 & 3.0000 & 2.9100 & 2.7500 & 2.5100 & 2.1900\\
2 & 2.1569 & 2.0132 & 1.6662 & 1.1157 & 0.3963\\
4 & 1.3268 & 1.3902 & 1.2218 & 0.8508 & 0.3036\\
\bottomrule
\end{tabular}
\end{table}

\section{Variance under AR(1): moment-based approach}\label{variance-under-ar1-moment-based-approach}

\subsection{Cross-covariance between phase means}\label{cross-covariance-between-phase-means}

\begin{orig}
An alternative to the GLS approach computes the
variance of the pre-post test statistic directly
from the moments of the phase means, following the
summary-measures approach of\textsuperscript{\citeproc{ref-frison1992}{10}}, specialized
here to AR(1) correlation. Let
\(\bar{X}_0 = \frac{1}{J_0}\sum_{i=1}^{J_0} Y_{i,\text{run-in}}\)
and
\(\bar{X}_K = \frac{1}{J_1}\sum_{j=1}^{J_1} Y_{j,\text{trt}}\)
denote the run-in and treatment-period means.

\end{orig}

Under AR(1) with parameter \(c = \rho\), the
cross-covariance is:
\begin{equation}
  \mathop{\mathrm{Cov}}(\bar{X}_0, \bar{X}_K)
  = \frac{\sigma^2}{J_0 J_1}\,\rho\, c^{K-1}\,
    \frac{(1 - c^{J_0})(1 - c^{J_1})}{(1 - c)^2}
\end{equation}
where \(c = \rho\) (the symbol \(c\) here denotes the
autocorrelation and is unrelated to the
reparameterization \(c = \sigma^2 - \sigma_b^2 t^2\) used
in Paper 1) and \(K\) is the time-index lag from the last
run-in visit to the first treatment visit on the visit
grid \(d = (-J_0, \ldots, -1, 1, \ldots, J_1)\). Because
baseline (time 0) is not itself a phase observation,
adjacent phases have \(K = 2\). The division by
\(J_0 J_1\) reflects that \(\bar{X}_0\) and \(\bar{X}_K\) are
means of \(J_0\) and \(J_1\) observations respectively; this
matches the implementation in \texttt{ar1\_cov\_phase\_means()}
below.

\subsection{Variance of the change score}\label{variance-of-the-change-score}

The variance of the pre-post difference is:
\begin{equation}
  \mathop{\mathrm{Var}}(X_K - X_0) = \mathop{\mathrm{Var}}(X_K) + \mathop{\mathrm{Var}}(X_0)
    - 2\mathop{\mathrm{Cov}}(X_K, X_0)
\end{equation}

The variance of each phase mean involves the sum
\(S_n = \sum_{i=1}^{n-1}(n-i)c^{i-1}\), which has the
closed form:
\begin{equation}
  S_n = \frac{n(1-c) - (1-c^n)}{(1-c)^2}
\end{equation}

\begin{verbatim}
## Moment-based vs GLS variance (r=2, k=2, rho=0.5):
\end{verbatim}

\begin{verbatim}
##   Moment-based phase-mean difference: 1.2188
\end{verbatim}

\begin{verbatim}
##   GLS slope difference (sigma_b2=0):  0.6364
\end{verbatim}

\begin{verbatim}
##   GLS slope difference (sigma_b2=1):  1.6662
\end{verbatim}

\begin{verbatim}
##   (Different estimands; see next section.)
\end{verbatim}

\section{Relationship between the two approaches}\label{relationship-between-the-two-approaches}

\begin{orig}
The GLS approach (Section 3) and the moment-based
approach (Section 4) compute different quantities.
The GLS variance is the minimum-variance bound under
the assumed model, while the moment-based variance
is the variance of the simple averaged change-score
estimator \(\bar{d}_1 - \bar{d}_0\).

\end{orig}

\begin{orig}
The two approaches do not coincide even when
\(\sigma_b^2 = 0\). At that boundary the GLS estimator
still weights the change scores through the AR(1)
residual covariance and estimates the slope-difference
parameter \(\gamma\), whereas the moment-based quantity is
the variance of the unweighted phase-mean difference
\(\bar{X}_K - \bar{X}_0\). With \(J_0 = 2\), \(J_1 = 2\),
\(\rho = 0.5\), \(\sigma^2 = 1\), and \(\sigma_b^2 = 0\), the
GLS variance is 0.636 while the moment-based variance
is 1.219. When \(\sigma_b^2 > 0\) the GLS estimator
additionally exploits the random-slope structure of
\(\Sigma = R + ZGZ'\).

\end{orig}

\begin{orig}
The practical value of the moment-based computation is
that it requires no specification of \(\sigma_b^2\) and
gives the exact variance of the simple pre-post
difference that an analyst might report without fitting
a mixed model. It is not a bound on the GLS variance: at
the parameters above the moment-based value (1.219) lies
between the GLS variance at \(\sigma_b^2 = 0\) (0.636) and
at \(\sigma_b^2 = 1\) (1.666). Because the two quantities
are variances of different estimands, their ratio
describes the cost of abandoning the mixed model rather
than an efficiency ordering within it. The
relative-efficiency question is taken up in Paper 4.

\end{orig}

\section{Robustness to correlation misspecification}\label{robustness-to-correlation-misspecification}

The practical question is whether a trial designed
under compound symmetry loses substantial efficiency
when the true correlation is AR(1), and vice versa.
Throughout this section the two structures are matched
at a common nominal correlation parameter \(\rho\); the
comparison, and its direction, depend on this matching
convention.

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:robustness}Ratio of AR(1) to compound-symmetry variance at a matched nominal \textbackslash rho for three run-in configurations (J\_1=2, J\_2=0, \textbackslash sigma\^{}2=1, \textbackslash sigma\_b\^{}2=1). The ratio remains near or below one except at J\_0=4 and small \textbackslash rho, where it peaks near 1.06.}]{report_files/report_files/figure-latex/robustness-1.pdf}}
\caption{\label{fig:robustness}Ratio of AR(1) to compound-symmetry variance at a matched nominal \(\rho\) for three run-in configurations (\(J_1=2\), \(J_2=0\), \(\sigma^2=1\), \(\sigma_b^2=1\)). The ratio remains near or below one except at \(J_0=4\) and small \(\rho\), where it peaks near 1.06.}
\end{figure}

\section{Stratified variance for unequal visit patterns}\label{stratified-variance-for-unequal-visit-patterns}

When participants have different numbers of run-in
(\(J_{0,i}\)) or common close (\(J_{2,i}\)) observations, the
total variance is a weighted sum across strata:
\begin{equation}
  \frac{1}{n^2}\sum_{s=1}^{S} n_s\,
    \mathop{\mathrm{Var}}(X_K - X_0)\big|_{J_0 = J_{0,s},\, J_2 = J_{2,s}}
\end{equation}

\section{Numerical examples}\label{numerical-examples}

\subsection{Comparison across correlation structures}\label{comparison-across-correlation-structures}

\begin{table}

\caption{\label{tab:comparison}Sample size per group (MIRIAD parameters, $\Delta=0.25$, 90\% power) under compound symmetry vs AR(1).}
\centering
\begin{tabular}[t]{rrrrr}
\toprule
$J_0$ & $J_1$ & $J_2$ & $N$ (CS) & $N$ (AR(1), $\rho=0.5$)\\
\midrule
0 & 2 & 0 & 385 & 371\\
1 & 2 & 0 & 247 & 157\\
2 & 2 & 0 & 145 & 107\\
3 & 2 & 0 & 100 & 85\\
4 & 2 & 0 & 78 & 72\\
\bottomrule
\end{tabular}
\end{table}

At the matched nominal \(\rho = 0.5\), the AR(1) sample
sizes are smaller than the compound-symmetric ones at
every \(J_0\), by 3.6\% (\(J_0 = 0\)) to 36.4\%
(\(J_0 = 1\)). Positive serial correlation reduces the
residual variance of each change score
(\(R_{jj} = 2\sigma^2(1 - \rho^{|j|}) < 2\sigma^2\)), so
the compound-symmetric calculation, which corresponds
to independent raw errors, is conservative here.

\subsection{Sensitivity to rho}\label{sensitivity-to-rho}

\begin{figure}
\centering
\pandocbounded{\includegraphics[keepaspectratio,alt={\label{fig:sensitivity}Per-pair variance as a function of \textbackslash rho under AR(1) for MIRIAD parameters (\textbackslash sigma\^{}2=0.3363, \textbackslash sigma\_b\^{}2=0.9745, J\_1=2, J\_2=0).}]{report_files/report_files/figure-latex/sensitivity-1.pdf}}
\caption{\label{fig:sensitivity}Per-pair variance as a function of \(\rho\) under AR(1) for MIRIAD parameters (\(\sigma^2=0.3363\), \(\sigma_b^2=0.9745\), \(J_1=2\), \(J_2=0\)).}
\end{figure}

\section{Discussion}\label{discussion}

\begin{orig}
The central practical question is when the compound-symmetry
formulas of Paper 1 can be used in place of the AR(1)
formulas derived here. The numerical comparisons indicate
that the answer is governed by the same slope-to-noise ratio
\(\sigma_b^2 t^2 / \sigma^2\) that governs the value of run-in
observations themselves. When this ratio is large, the random
slope term \(Z G Z'\) dominates the change-score covariance
\(\Sigma = R + Z G Z'\), the residual term \(R\) contributes
little, and the choice between an AR(1) and a
compound-symmetric \(R\) is immaterial. When the ratio is small,
the residual term dominates and the correlation structure
becomes the leading determinant of efficiency.

\end{orig}

\begin{orig}
The direction of the error is important for trial design.
When the two structures are matched at a common nominal
\(\rho\), positive serial correlation reduces the residual
variance of every change score
(\(R_{jj} = 2\sigma^2(1 - \rho^{|j|})\)), so the AR(1)
variance lies below the compound-symmetric value for most
configurations and the compound-symmetric sample size is
conservative. In the MIRIAD example at \(\rho = 0.5\) the
AR(1) sample sizes are 4 to 36 percent smaller than the
compound-symmetric ones, and the gap widens as \(\rho\)
grows. The exception is a narrow regime with many run-in
observations and low autocorrelation (\(J_0 = 4\),
\(\rho \approx 0.2\)), where correlation decay makes
distant run-in observations less informative than
compound symmetry credits them to be; there the
compound-symmetric formula understates the variance, by
at most about 6 percent in the configurations examined.
Both statements are specific to the
common-nominal-\(\rho\) matching convention; matching the
structures on, for example, a common lag-one
change-score correlation would alter the comparison.

\end{orig}

\begin{orig}
For applied use we recommend the following. At a matched
nominal \(\rho\), the compound-symmetry formula of Paper 1
is conservative for most designs and can serve as a
convenient default; the AR(1) formula then refines the
sample size downward. When the design places many run-in
observations before randomization and the expected
autocorrelation is low, the AR(1) formula should be used
directly, because the compound-symmetric formula can
understate the variance by up to about 6 percent in that
regime. When the correlation structure cannot be pinned
down from prior data, evaluating the AR(1) formula over
a plausible range of \(\rho\) and taking the largest
resulting variance yields a safe sample size. The
moment-based computation of Section 4 addresses the
simple pre-post estimator and is not a bound on the GLS
variance.

\end{orig}

\section{Conflict of interest}\label{conflict-of-interest}

The author declares no conflicts of interest.

\section{Funding}\label{funding}

This work received no specific funding.

\section{Data availability statement}\label{data-availability-statement}

\begin{orig}
The \texttt{runinpower} R package implementing the AR(1) variance
formulas (\texttt{covariance-ar1.R}), validation tests, and the
shared bibliography across the four-paper compendium are
openly available in the project repository. Specific paths
are listed in the Reproducibility section below.

\end{orig}

\section{Reproducibility}\label{reproducibility}

\begin{orig}
This manuscript was rendered with R 4.4.x. Principal packages
used are the in-package \texttt{runinpower} source (the AR(1)
machinery is in \texttt{covariance-ar1.R}), \texttt{tinytest} (testing
harness), and \texttt{rmarkdown} plus \texttt{bookdown} for the manuscript
build.

\end{orig}

\begin{orig}
\textbf{Random-number generator.} The AR(1) variance formulas
are deterministic given fixed input parameters; no
random-number generation is used anywhere in this
manuscript, and re-running the code chunks reproduces
every table and figure exactly.

\end{orig}

\begin{orig}
\textbf{Data and code availability.} The R package source is at
\texttt{R/}. The companion manuscripts (Papers 1, 3, 4) are at
\texttt{analysis/report/\{01,03,04\}-*/}. The manuscript source and
shared bibliography (\texttt{references.bib}, a symlink to
\texttt{../../references.bib}) are at
\texttt{analysis/report/02-correlation/}.

\end{orig}

\section{References}\label{references}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{0}{1}
\bibitem[\citeproctext]{ref-frost2008}
\CSLLeftMargin{1. }%
\CSLRightInline{Frost C, Kenward MG, Fox NC. Optimizing the design of clinical trials where the outcome is a rate. {Can} estimating a baseline rate in a run-in period increase efficiency? \emph{Statistics in Medicine}. 2008;27(18):3717-3731. doi:\href{https://doi.org/10.1002/sim.3280}{10.1002/sim.3280}}

\bibitem[\citeproctext]{ref-wang2019}
\CSLLeftMargin{2. }%
\CSLRightInline{Wang G, Aschenbrenner AJ, Li Y, et al. Two-period linear mixed effects models to analyze clinical trials with run-in data when the primary outcome is continuous: {Applications} to {Alzheimer's} disease. \emph{Alzheimer's \& Dementia: Translational Research \& Clinical Interventions}. 2019;5:450-457. doi:\href{https://doi.org/10.1016/j.trci.2019.08.002}{10.1016/j.trci.2019.08.002}}

\bibitem[\citeproctext]{ref-winkens2007}
\CSLLeftMargin{3. }%
\CSLRightInline{Winkens B, Breukelen GJP van, Schouten HJA, Berger MPF. Randomized clinical trial designs for auto-correlated longitudinal data. \emph{Statistics in Medicine}. 2007;26(28):5023-5037. doi:\href{https://doi.org/10.1002/sim.2907}{10.1002/sim.2907}}

\bibitem[\citeproctext]{ref-diggle2002}
\CSLLeftMargin{4. }%
\CSLRightInline{Diggle PJ, Heagerty P, Liang KY, Zeger SL. \emph{Analysis of Longitudinal Data}. 2nd ed. Oxford University Press; 2002.}

\bibitem[\citeproctext]{ref-verbeke2000}
\CSLLeftMargin{5. }%
\CSLRightInline{Verbeke G, Molenberghs G. \emph{Linear Mixed Models for Longitudinal Data}. Springer; 2000.}

\bibitem[\citeproctext]{ref-munoz1992}
\CSLLeftMargin{6. }%
\CSLRightInline{Muñoz A, Carey V, Schouten JP, Segal M, Rosner B. A parametric family of correlation structures for the analysis of longitudinal data. \emph{Biometrics}. 1992;48(3):733-742. doi:\href{https://doi.org/10.2307/2532340}{10.2307/2532340}}

\bibitem[\citeproctext]{ref-chambless1993}
\CSLLeftMargin{7. }%
\CSLRightInline{Chambless LE, Roeback JR. Methods for assessing difference between groups in change when initial measurement is subject to intra-individual variation. \emph{Statistics in Medicine}. 1993;12(14):1213-1237. doi:\href{https://doi.org/10.1002/sim.4780121403}{10.1002/sim.4780121403}}

\bibitem[\citeproctext]{ref-iddi2022}
\CSLLeftMargin{8. }%
\CSLRightInline{Iddi S, Donohue MC. Power and sample size for longitudinal models in {R} -- the longpower package and {Shiny} app. \emph{The R Journal}. 2022;14(1):264-282. \url{https://journal.r-project.org/articles/RJ-2022-022/}}

\bibitem[\citeproctext]{ref-lu2008}
\CSLLeftMargin{9. }%
\CSLRightInline{Lu K, Luo X, Chen PY. Sample size estimation for repeated measures analysis in randomized clinical trials with missing data. \emph{International Journal of Biostatistics}. 2008;4(1):Article 9. doi:\href{https://doi.org/10.2202/1557-4679.1098}{10.2202/1557-4679.1098}}

\bibitem[\citeproctext]{ref-frison1992}
\CSLLeftMargin{10. }%
\CSLRightInline{Frison L, Pocock SJ. Repeated measures in clinical trials: Analysis using mean summary statistics and its implications for design. \emph{Statistics in Medicine}. 1992;11(13):1685-1704. doi:\href{https://doi.org/10.1002/sim.4780111304}{10.1002/sim.4780111304}}

\end{CSLReferences}

\end{document}
